<a href="https://colab.research.google.com/github/AliRizvi14/CE888/blob/master/lab6/recommended_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [10]:
df=pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv', header=None)
df

0      1      2      3      4     5      6     7     8      9    ...  \
0       74  -7.82   8.79  -9.66  -8.16 -7.52  -8.50 -9.85  4.17  -8.98  ...   
1      100   4.08  -0.29   6.36   4.37 -2.38  -9.66 -0.73 -5.34   8.88  ...   
2       49  99.00  99.00  99.00  99.00  9.03   9.27  9.03  9.27  99.00  ...   
3       48  99.00   8.35  99.00  99.00  1.80   8.16 -2.82  6.21  99.00  ...   
4       91   8.50   4.61  -4.17  -5.39  1.36   1.60  7.04  4.61  -0.44  ...   
...    ...    ...    ...    ...    ...   ...    ...   ...   ...    ...  ...   
24978  100   0.44   7.43   9.08   2.33  3.20   6.75 -8.79 -0.53  -8.74  ...   
24979   91   9.13  -8.16   8.59   9.08  0.87  -8.93 -3.50  5.78  -8.11  ...   
24980   39  99.00  99.00  99.00  99.00 -7.77  99.00  6.70 -6.75  99.00  ...   
24981   37  99.00  99.00  99.00  99.00 -9.71  99.00  4.56 -8.30  99.00  ...   
24982   72   2.43   2.67  -3.98   4.27 -2.28   7.33  2.33  4.56   6.75  ...   

         91     92     93     94     95     96     97     98     99     100  
0       2.82  99.00  99.00  99.00  99.00  99.00  -5.63  99.00  99.00  99.00  
1       2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
2      99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
3      99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
4       5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
24978   8.83  -1.21   9.22  -6.70   8.45   9.03   6.55   8.69   8.79   7.43  
24979  -1.17  -5.73  -1.46   0.24   9.22  -8.20  -7.23  -8.59   9.13   8.45  
24980  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  
24981  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  
24982  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  

[24983 rows x 101 columns]

In [15]:
df= df.replace(99.00, np.nan)
# to drop column
df = df.iloc[: , 1:] # Remove first column which consist number of jokes rated by the user

In [24]:
df

1     2     3     4     5     6     7     8     9     10   ...   91   \
0     -7.82  8.79 -9.66 -8.16 -7.52 -8.50 -9.85  4.17 -8.98 -4.76  ...  2.82   
1      4.08 -0.29  6.36  4.37 -2.38 -9.66 -0.73 -5.34  8.88  9.22  ...  2.82   
2       NaN   NaN   NaN   NaN  9.03  9.27  9.03  9.27   NaN   NaN  ...   NaN   
3       NaN  8.35   NaN   NaN  1.80  8.16 -2.82  6.21   NaN  1.84  ...   NaN   
4      8.50  4.61 -4.17 -5.39  1.36  1.60  7.04  4.61 -0.44  5.73  ...  5.19   
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
24978  0.44  7.43  9.08  2.33  3.20  6.75 -8.79 -0.53 -8.74  7.23  ...  8.83   
24979  9.13 -8.16  8.59  9.08  0.87 -8.93 -3.50  5.78 -8.11  4.90  ... -1.17   
24980   NaN   NaN   NaN   NaN -7.77   NaN  6.70 -6.75   NaN   NaN  ...   NaN   
24981   NaN   NaN   NaN   NaN -9.71   NaN  4.56 -8.30   NaN   NaN  ...   NaN   
24982  2.43  2.67 -3.98  4.27 -2.28  7.33  2.33  4.56  6.75  4.61  ...   NaN   

        92    93    94    95    96    97    98    99    100  
0       NaN   NaN   NaN   NaN   NaN -5.63   NaN   NaN   NaN  
1     -4.95 -0.29  7.86 -0.19 -2.14  3.06  0.34 -4.32  1.07  
2       NaN   NaN  9.08   NaN   NaN   NaN   NaN   NaN   NaN  
3       NaN   NaN  0.53   NaN   NaN   NaN   NaN   NaN   NaN  
4      5.58  4.27  5.19  5.73  1.55  3.11  6.55  1.80  1.60  
...     ...   ...   ...   ...   ...   ...   ...   ...   ...  
24978 -1.21  9.22 -6.70  8.45  9.03  6.55  8.69  8.79  7.43  
24979 -5.73 -1.46  0.24  9.22 -8.20 -7.23 -8.59  9.13  8.45  
24980   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
24981   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
24982   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[24983 rows x 100 columns]

In [33]:
m=df.iloc[0,:].values
l=len(m)
s=m.sum()
avg=s/l
avg

nan

In [17]:
df.describe()

1             2             3             4             5    \
count  16452.000000  18184.000000  16642.000000  15608.000000  24977.000000   
mean       0.904573      0.208460      0.316574     -1.449114      0.403556   
std        5.171798      5.597327      5.399806      5.234654      5.255700   
min       -9.950000     -9.950000     -9.950000     -9.950000     -9.950000   
25%       -2.670000     -4.420000     -4.030000     -5.870000     -3.690000   
50%        1.600000      0.830000      0.780000     -1.460000      1.120000   
75%        4.900000      4.820000      4.660000      2.520000      4.470000   
max        9.370000      9.370000      9.370000      9.370000      9.370000   

                6             7             8             9             10   \
count  20431.000000  24976.000000  24981.000000  15752.000000  20324.000000   
mean       1.594447     -0.429662     -0.624085     -0.557031      1.301231   
std        4.900540      5.495931      4.929144      5.162224      5.087359   
min       -9.950000     -9.950000     -9.950000     -9.950000     -9.950000   
25%       -1.310000     -5.290000     -4.610000     -4.760000     -2.090000   
50%        2.230000     -0.050000     -0.290000     -0.190000      1.940000   
75%        5.440000      3.880000      3.060000      3.300000      5.390000   
max        9.470000      9.610000      9.760000      9.900000      9.370000   

       ...          91           92           93            94            95   \
count  ...  9672.000000  9889.000000  9988.000000  10200.000000  10265.000000   
mean   ...     2.038527     1.179744     2.504041      1.173482      1.039130   
std    ...     5.060445     5.127291     4.611339      5.140307      5.167043   
min    ...    -9.950000    -9.950000    -9.950000     -9.950000     -9.950000   
25%    ...    -0.932500    -2.380000    -0.100000     -2.280000     -2.570000   
50%    ...     2.860000     1.800000     3.160000      1.750000      1.650000   
75%    ...     6.120000     5.290000     6.070000      5.290000      5.100000   
max    ...     9.560000     9.420000     9.370000      9.420000      9.370000   

                96            97            98            99           100  
count  10370.000000  10520.000000  10666.000000  10910.000000  9943.000000  
mean       1.528003      1.673750      0.767692     -0.031244     1.354711  
std        4.852069      5.025076      5.393833      5.176806     5.300409  
min       -9.950000     -9.950000     -9.950000     -9.950000    -9.950000  
25%       -1.347500     -1.170000     -3.400000     -4.170000    -2.330000  
50%        2.140000      2.480000      1.460000      0.290000     2.140000  
75%        5.277500      5.630000      5.150000      3.980000     5.730000  
max        9.370000      9.370000      9.370000      9.370000     9.370000  

[8 rows x 100 columns]

In [18]:
df.mean().sort_values(ascending=True)

58   -3.833880
16   -3.104818
44   -2.111891
57   -1.990664
13   -1.762882
        ...   
32    3.155988
27    3.189821
36    3.312500
89    3.574720
50    3.665085
Length: 100, dtype: float64

In [19]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)


In [23]:
arr = df.values
arr
#print(arr.shape)

array([[-7.82,  8.79, -9.66, ...,   nan,   nan,   nan],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [ 2.43,  2.67, -3.98, ...,   nan,   nan,   nan]])

In [44]:
rated = np.where(arr!=99)
print(len(rated[0]), rated[1].shape)

2498300 (2498300,)


In [35]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(arr!=99)
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [45]:
new_arr, idx = replace(arr, 0.1)

In [46]:
new_arr

array([[-7.82,  8.79, 99.  , ...,   nan,   nan,   nan],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan,   nan, 99.  , ...,   nan, 99.  ,   nan],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [99.  ,  2.67, -3.98, ...,   nan,   nan,   nan]])

In [37]:
arr[idx[0][0], idx[1][0]]

nan

In [38]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [52]:
data = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/user_ratings.csv")
data

The Call of Cthulhu   Frankenstein   Dracula   Neuromancer   Space Odyssey
0                  8.0            2.0       NaN           5.0             4.0
1                  3.0            2.0       NaN           7.0             7.0
2                  9.0            NaN       7.0           8.0             5.0
3                  NaN            NaN       7.0           8.0             9.0
4                  NaN            1.0       8.0           3.0             7.0
5                  2.0            3.0       5.0           NaN             NaN
6                  4.0            2.0       NaN           2.0             7.0
7                  7.0            1.0       2.0           7.0             9.0
8                  3.0            3.0       NaN           7.0             3.0
9                  4.0            NaN       5.0           3.0             3.0

In [53]:
n_latent_factors = 2

user_ratings = data.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [54]:
latent_item_features

array([[0.171, 0.541],
       [0.182, 0.886],
       [0.671, 0.067],
       [0.881, 0.672],
       [0.472, 0.135]])

In [57]:
data.values.shape[1]



5

In [58]:
latent_user_preferences

array([[0.842, 0.612],
       [0.009, 0.434],
       [0.467, 0.39 ],
       [0.495, 0.387],
       [0.741, 0.863],
       [0.625, 0.537],
       [0.278, 0.214],
       [0.691, 0.831],
       [0.829, 0.811],
       [0.861, 0.695]])

In [59]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                if not np.isnan(rating):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10000) == 0:
            print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
            mse_history.append(mse)
    return mse_history
num_iter = 300000
hist = sgd(num_iter)  # Note how the MSE decreases with the number of i

Iteration 0/300000:	MSE=25.551134
Iteration 10000/300000:	MSE=1.364294
Iteration 20000/300000:	MSE=1.268371
Iteration 30000/300000:	MSE=1.234475
Iteration 40000/300000:	MSE=1.219054
Iteration 50000/300000:	MSE=1.211665
Iteration 60000/300000:	MSE=1.207988
Iteration 70000/300000:	MSE=1.206084
Iteration 80000/300000:	MSE=1.205052
Iteration 90000/300000:	MSE=1.204465
Iteration 100000/300000:	MSE=1.204111
Iteration 110000/300000:	MSE=1.203886
Iteration 120000/300000:	MSE=1.203734
Iteration 130000/300000:	MSE=1.203627
Iteration 140000/300000:	MSE=1.203547
Iteration 150000/300000:	MSE=1.203487
Iteration 160000/300000:	MSE=1.203439
Iteration 170000/300000:	MSE=1.203400
Iteration 180000/300000:	MSE=1.203369
Iteration 190000/300000:	MSE=1.203343
Iteration 200000/300000:	MSE=1.203322
Iteration 210000/300000:	MSE=1.203304
Iteration 220000/300000:	MSE=1.203289
Iteration 230000/300000:	MSE=1.203276
Iteration 240000/300000:	MSE=1.203266
Iteration 250000/300000:	MSE=1.203257
Iteration 260000/300000:	

In [ ]:
num_iter = 300000
hist = sgd(num_iter)  # Note how the MSE decreases with the number of iterations
plt.figure()
plt.plot(np.arange(0, num_iter, 10000), hist)
plt.xlabel("Iterations")
plt.ylabel("MSE")
plt.show()

In [ ]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

In [ ]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = data.columns

In [ ]:
comparison_data
# For each data point, the number on the left is the original value from the dataset, the number on the right is the prediction

In [ ]:
#Answers

df_factor2 = df_movies[['Movie ID','Factor15']]
df_factor2.sort_values('Factor15')

In [ ]:
# Q7
# In the movies dataset, what's the loading (i.e., value) of Factor15 for user with ID=4997?
num_factors = df_users.shape[1]-1
user_pref = df_users[df_users['User'] == 4997].iloc[:, -num_factors:].values[0]
item_feat = df_movies.iloc[:, -num_factors:].values

df_movies[df_movies['Movie ID']==597].index.values[0]

In [ ]:
#Question 5

df_factor = df_movies[['Movie ID','Factor5']]

value = df_factor[df_factor['Movie ID']==10020]['Factor5'].values[0]
print(value)

round(value,3)

In [ ]:
#Question 7 and 8

num_factors = df_users.shape[1]-1
user_pref = df_users[df_users['User'] == 4997].iloc[:, -num_factors:].values[0]
item_feat = df_movies.iloc[:, -num_factors:].values

In [ ]:
df_users[df_users['User']==4997]

In [ ]:
# Q7
df_users[df_users['User']==4997]

In [ ]:
# Q8
df_movies[['Movie ID','Factor4', 'Title']].sort_values('Factor4')

In [ ]:
a = df_users[df_users['User']==3519].iloc[:, 1:].values
a

In [ ]:
#df_movies['Movie ID']==809]
b = df_movies[df_movies['Movie ID']==809].iloc[:, 2:].values
b

In [ ]:
#Calculates the dot product between the User,movie and the factor. Change User/Movie/factor to compare two
np.array(df_users[df_users['User'] == 3519].iloc[:, 1:].values).dot(np.array(df_movies[df_movies['Movie ID']==809].iloc[:, 2:].values).reshape(-1,1))

In [ ]:
# In the movies dataset, if you had to recommend 2 movies to the user with ID=3519, which ones would you choose?
a = np.array(df_users[df_users['User'] == 3519].iloc[:, 1:].values).dot(np.array(df_movies.iloc[:, 2:].values.T))

In [ ]:
np.argsort(a)

In [ ]:
a.shape

In [ ]:
np.sort(a)

In [ ]:
# In the movies dataset, if you had to recommend 2 movies to the user with ID=2067, which ones would you choose?
b = np.array(df_users[df_users['User'] == 2067].iloc[:, 1:].values).dot(np.array(df_movies.iloc[:, 2:].values.T))

In [ ]:
np.argsort(b)

In [ ]:
# In the movies dataset, if you had to recommend 2 movies to the user with ID=3519, which ones would you choose?
df_users[df_users['User']==3519]

In [ ]:
#df_jester.sort_values(by=df_jester[0], ascending=True)
#df_jester[0].sort_values(ascending=True)
df_movies.head(15)
